[tool.poetry]
name = "elite-qualifer"
version = "0.1.0"
description = ""
authors = ["PhantomCloud <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pyspellchecker = "^0.6.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
